<?php

namespace AppBundle\Repository;

/**
 * WhitelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhitelistRepository extends \Doctrine\ORM\EntityRepository
{
}
